In [1]:
import pandas as pd

df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\Bengaluru_House_Data.csv")
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [18]:
df.dtypes

area_type        object
availability     object
location         object
size             object
society          object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object

In [19]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [3]:
df['area_type'].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [4]:
df['availability'].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
       '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
       '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
       '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
       '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
       '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
       '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [26]:
df[df['location'].isna()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
568,Super built-up Area,Ready To Move,NaN,3 BHK,Grare S,1600,3.0,2.0,86.0

In [5]:
# Remove duplicate properties

df['location'] = df['location'].fillna('Unknown')
df.dropna(subset=['location'], inplace=True)
df['location'].isna().sum()

np.int64(0)

In [6]:
# • Standardize locations
df['location'] = df['location'].str.strip().str.title()
df['location'].unique()

array(['Electronic City Phase Ii', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12Th Cross Srinivas Nagar Banshankari 3Rd Stage',
       'Havanur Extension', 'Abshot Layout'], shape=(1284,), dtype=object)

In [7]:
df['size'].isna().sum()

np.int64(16)

In [8]:
df[df['size'].isna()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
579,Plot Area,Immediate Possession,Sarjapur Road,NaN,Asiss B,1200 - 2400,NaN,NaN,34.185
1775,Plot Area,Immediate Possession,Ivc Road,NaN,Orana N,2000 - 5634,NaN,NaN,124.000
2264,Plot Area,Immediate Possession,Banashankari,NaN,NaN,2400,NaN,NaN,460.000
2809,Plot Area,Immediate Possession,Sarjapur Road,NaN,AsdiaAr,1200 - 2400,NaN,NaN,28.785
2862,Plot Area,Immediate Possession,Devanahalli,NaN,Ajleyor,1500 - 2400,NaN,NaN,46.800
5333,Plot Area,Immediate Possession,Devanahalli,NaN,Emngs S,2100 - 5405,NaN,NaN,177.115
6423,Plot Area,Immediate Possession,Whitefield,NaN,SRniaGa,2324,NaN,NaN,26.730
6636,Plot Area,Immediate Possession,Jigani,NaN,S2enste,1500,NaN,NaN,25.490
6719,Plot Area,Immediate Possession,Hoskote,NaN,SJowsn,800 - 2660,NaN,NaN,28.545
7680,Plot Area,Immediate Possession,Kasavanhalli,NaN,NaN,5000,NaN,NaN,400.000
8306,Plot Area,Immediate Possession,Anekal,NaN,Vaensnd,1453,NaN,NaN,16.500
8565,Plot Area,Immediate Possession,Carmelaram,NaN,Ocezes,2000,NaN,NaN,120.000
8703,Plot Area,Immediate Possession,Mysore Road,NaN,Naoden,1200 - 2400,NaN,NaN,42.300
10634,Plot Area,Immediate Possession,Rajankunte,NaN,NaN,1575,NaN,NaN,31.110
11019,Plot Area,Immediate Possession,Yelahanka,NaN,Saaveha,1200 - 1800,NaN,NaN,12.750
11569,Plot Area,Immediate Possession,Hosur Road,NaN,AVeldun,1350,NaN,NaN,8.440

In [39]:
df['size'] = df['size'].fillna('Unknown')
df.dropna(subset=['size'], inplace=True)
df['size'].isna().sum()

np.int64(0)

In [9]:
df['society'].isna().sum()

np.int64(5502)

In [10]:
df['size'] = df['size'].str.replace('Bedroom', 'BHK', regex=False)
df['size'] = df['size'].str.replace('Unknown', ' ', regex=False)
df['size'].unique()

array(['2 BHK', '4 BHK', '3 BHK', '6 BHK', '1 BHK', '1 RK', '8 BHK',
       '7 BHK', '5 BHK', '11 BHK', '9 BHK', nan, '27 BHK', '10 BHK',
       '19 BHK', '16 BHK', '43 BHK', '14 BHK', '12 BHK', '13 BHK',
       '18 BHK'], dtype=object)

In [12]:
df = df.dropna(subset=['society'])
df['society'] = df['society'].fillna('Unknown')
df['society'].isna().sum()

np.int64(0)

In [13]:
df.isnull().sum()

area_type         0
availability      0
location          0
size             13
society           0
total_sqft        0
bath             70
balcony         321
price             0
dtype: int64

In [14]:
df['total_sqft'].isna().sum()

np.int64(0)

In [15]:
#  Extract area from 1,250 sqft

df = df.dropna(subset=['total_sqft'])
df['total_sqft'] = df['total_sqft'].fillna('Unknown')
df['total_sqft'].isna().sum()

np.int64(0)

In [16]:
df['total_sqft'] = pd.to_numeric(df['total_sqft'], errors='coerce')
df['total_sqft'].dtype

dtype('float64')

In [17]:
df['bath'].unique()

array([ 2.,  5.,  3.,  4.,  1., nan,  6.,  9.,  7., 14., 10., 18.])

In [18]:
# Handle missing bedrooms/bathrooms
df = df.dropna(subset=['bath'])
df['bath'] = df['bath'].fillna('Unknown')
df['bath'].isna().sum()

np.int64(0)

In [19]:
df['balcony'].isnull().sum()

np.int64(251)

In [20]:
df = df.dropna(subset=['balcony'])
df['balcony'] = df['balcony'].fillna('Unknown')
df['balcony'].isnull().sum()

np.int64(0)

In [84]:
df['price'].isnull().sum()

np.int64(0)

In [90]:
# Convert ₹85 Lakh, ₹1.2 Cr into numeric values
df['price'] = df['price'].astype(str)

df['price'] = df['price'].str.replace('₹', '', regex=False)
df['price'] = df['price'].str.replace(',', '', regex=False)

In [92]:
def convert_price(x):
    if 'Lakh' in x:
        return float(x.replace('Lakh', '')) * 100000
    elif 'Cr' in x:
        return float(x.replace('Cr', '')) * 10000000
    else:
        return float(x)

df['price'] = df['price'].astype(str)
df['price'] = df['price'].apply(convert_price)

In [97]:
# Detect price outliers
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

price_outliers = df[(df['price'] < lower) | (df['price'] > upper)]

price_outliers

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
11,Plot Area,Ready To Move,Whitefield,4 BHK,Prrry M,2785.0,5.0,3.0,295.0
18,Super built-up Area,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.0
22,Plot Area,Ready To Move,Thanisandra,4 BHK,Soitya,2800.0,5.0,2.0,380.0
62,Plot Area,Ready To Move,Whitefield,4 BHK,Chranya,5700.0,5.0,3.0,650.0
77,Built-up Area,Ready To Move,Cholanayakanahalli,3 BHK,Viony H,2511.0,3.0,3.0,205.0
...,...,...,...,...,...,...,...,...,...
13269,Plot Area,Ready To Move,Electronic City,3 BHK,SJovest,2010.0,3.0,2.0,201.0
13290,Super built-up Area,Ready To Move,Sarjapur Road,4 BHK,Maana E,4050.0,2.0,1.0,450.0
13293,Super built-up Area,Ready To Move,Sarjapur Road,4 BHK,Puallhi,2425.0,5.0,1.0,195.0
13315,Built-up Area,Ready To Move,Whitefield,5 BHK,ArsiaEx,3453.0,4.0,0.0,231.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689.0,4.0,1.0,488.0

In [98]:
# Detect area outliers
Q1 = df['total_sqft'].quantile(0.25)
Q3 = df['total_sqft'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

area_outliers = df[(df['total_sqft'] < lower) | (df['total_sqft'] > upper)]

area_outliers

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
1,Plot Area,Ready To Move,Chikka Tirupathi,4 BHK,Theanmp,2600.0,5.0,3.0,120.0
11,Plot Area,Ready To Move,Whitefield,4 BHK,Prrry M,2785.0,5.0,3.0,295.0
18,Super built-up Area,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770.0,4.0,2.0,290.0
22,Plot Area,Ready To Move,Thanisandra,4 BHK,Soitya,2800.0,5.0,2.0,380.0
62,Plot Area,Ready To Move,Whitefield,4 BHK,Chranya,5700.0,5.0,3.0,650.0
...,...,...,...,...,...,...,...,...,...
13208,Super built-up Area,Ready To Move,Hebbal,4 BHK,Brium C,4000.0,6.0,1.0,370.0
13268,Super built-up Area,18-Apr,Epip Zone,4 BHK,BrontLa,3360.0,5.0,2.0,221.0
13290,Super built-up Area,Ready To Move,Sarjapur Road,4 BHK,Maana E,4050.0,2.0,1.0,450.0
13315,Built-up Area,Ready To Move,Whitefield,5 BHK,ArsiaEx,3453.0,4.0,0.0,231.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689.0,4.0,1.0,488.0

In [102]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase Ii,2 BHK,Coomee,1056.0,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 BHK,Theanmp,2600.0,5.0,3.0,120.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00
11,Plot Area,Ready To Move,Whitefield,4 BHK,Prrry M,2785.0,5.0,3.0,295.00
...,...,...,...,...,...,...,...,...,...
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345.0,2.0,1.0,57.00
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715.0,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 BHK,ArsiaEx,3453.0,4.0,0.0,231.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141.0,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689.0,4.0,1.0,488.00

In [100]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [105]:
# Which locations are most expensive?

df.groupby('location')['price'].mean().sort_values(ascending=False).head(10)

location
Yemlur               1245.000000
D Souza Layout       1015.000000
Shanthala Nagar       827.500000
Hunasamaranahalli     787.500000
Vasanth Nagar         721.500000
Cunningham Road       684.142857
Langford Gardens      649.500000
St. John'S Road       630.000000
Sathya Sai Layout     610.571429
Rahat Bagh            550.000000
Name: price, dtype: float64

In [21]:
#  Price per sqft by location?
df['price_per_sqft'] = df['price'] / df['total_sqft']
df['price_per_sqft']

0        0.036998
1        0.046154
3        0.062459
5        0.032479
11       0.105925
           ...
13313    0.042379
13314    0.065306
13315    0.066898
13317    0.052585
13318    0.104073
Name: price_per_sqft, Length: 7497, dtype: float64

In [104]:
df.to_csv("Bengaluru_House_Data.csv",index = False)

In [22]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase Ii,2 BHK,Coomee,1056.0,2.0,1.0,39.07,0.036998
1,Plot Area,Ready To Move,Chikka Tirupathi,4 BHK,Theanmp,2600.0,5.0,3.0,120.00,0.046154
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,0.062459
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00,0.032479
11,Plot Area,Ready To Move,Whitefield,4 BHK,Prrry M,2785.0,5.0,3.0,295.00,0.105925
...,...,...,...,...,...,...,...,...,...,...
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345.0,2.0,1.0,57.00,0.042379
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715.0,3.0,3.0,112.00,0.065306
13315,Built-up Area,Ready To Move,Whitefield,5 BHK,ArsiaEx,3453.0,4.0,0.0,231.00,0.066898
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141.0,2.0,1.0,60.00,0.052585
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689.0,4.0,1.0,488.00,0.104073