# Exam Task on Pandas Method (Data Cleaning)

In [1]:
# Part 1 — Inspect & Understand the Dataset
# Q1. Load the dataset
# Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
# Then display the first 10 rows.

import pandas as pd
df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\customer_analytics - customer_analytics.csv")
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 0:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 0:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 0:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 0:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 0:00:00,Yes,Medium,11472.36,124,9.1

In [2]:
# Q2. Inspect the end of the dataset
# Display the last 15 rows.
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 0:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 0:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 0:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 0:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 0:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 0:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 0:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 0:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 0:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 0:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [3]:
# Q3. Random inspection
# Display 10 random records.
df.sample()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1770,100113,62,86246,252517.01,314,2,Hyderabad,Corporate,Agent,2021-12-01 0:00:00,No,High,2985.55,86,9.9

In [4]:
# Q4. Dataset audit
# Use info() to identify:
# • Number of rows
# • Number of columns
# • Columns with missing values
# • Columns having incorrect/object datatypes
df1 = df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [9]:
# Q5. Missing-value audit
# Calculate the number of missing values in every column.
# Then verify the result using both:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [10]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

# Part 2 — Detect & Fix Data Quality Problems

In [14]:
# Q6. Duplicate investigation
# Find how many duplicate rows exist.
# Do not remove them yet.
df.duplicated().sum()

np.int64(40)

In [19]:
# Q7. Remove duplicates
# Remove all duplicate records and store the cleaned result back into df.
# Then verify that duplicates no longer exist.
df2 = df.drop_duplicates()
df2

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [26]:
# Q8. Numeric column investigation
# Select only numeric columns.
# Identify which columns are currently numeric and which potentially numeric columns have
# become object because of invalid values.
df2 = df.select_dtypes(include='number')
df2

      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2040 rows x 3 columns]

In [31]:
# Q9. Fix Age
# The Age column contains:
# • Valid numbers
# • Missing values
# • Invalid text such as unknown, N/A, etc.
# Convert Age into a proper numeric column.
# Invalid values should become missing values.
# Then fill missing Age values using the median age.
df["Age"]  = pd.to_numeric(df["Age"],errors = "coerce")
df["Age"]

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2040, dtype: float64

In [32]:
age_median= df['Age'].median()
age_median

47.0

In [34]:
age_median= df['Age'].fillna(age_median)
age_median

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2040, dtype: float64

In [38]:
# Q10. Fix Annual Income
#  Clean Annual_Income.
#  Requirements:
#  1. Convert invalid values to missing.
#  2. Convert the column to a numeric datatype.
#  3. Calculate the median.
#  4. Fill missing values using the median.
df["Annual_Income"]  = pd.to_numeric(df["Annual_Income"],errors = "coerce")
df["Annual_Income"]

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2040, dtype: float64

In [48]:
df['Annual_Income']=df['Annual_Income'].astype(float)
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [43]:
Income_median= df['Annual_Income'].median()
Income_median

139999.5

In [52]:
df['Annual_Income'] = df['Annual_Income'].fillna(Income_median)
df['Annual_Income']

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2040, dtype: float64

# Part 3 — Numerical Cleaning

In [53]:
# Q11. Clean Account Balance :
# The Account_Balance column contains invalid strings and missing values.
# Clean the column and replace missing values with the mean Account Balance.
df["Account_Balance"]  = pd.to_numeric(df["Account_Balance"],errors = "coerce")
df["Account_Balance"]

0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2040, dtype: float64

In [55]:
Income_mean= df['Account_Balance'].mean()
Income_mean

np.float64(151049.05422603106)

#### Q12. Clean Credit Score
#### Clean Credit_Score.
#### Invalid values should become missing.
#### Then replace missing values with the median Credit Score.
#### Finally convert the column to integer.

In [56]:
df["Credit_Score"]  = pd.to_numeric(df["Credit_Score"],errors = "coerce")
df["Credit_Score"]

0       772.0
1       374.0
2       668.0
3       315.0
4       370.0
        ...
2035    677.0
2036    392.0
2037    737.0
2038    794.0
2039    783.0
Name: Credit_Score, Length: 2040, dtype: float64

In [58]:
credit_median= df['Credit_Score'].median()
credit_median

570.0

In [65]:
df['Credit_Score'] = df['Credit_Score'].fillna(credit_median).astype(int)
df['Credit_Score']

0       772
1       374
2       668
3       315
4       370
       ...
2035    677
2036    392
2037    737
2038    794
2039    783
Name: Credit_Score, Length: 2040, dtype: int64

### Q13. Clean Monthly Spend
### Clean Monthly_Spend.
### Then:
### • Convert it to numeric.
### • Replace invalid values.
### • Replace missing values using the median.
### • Make sure the final column is numeric.

In [71]:
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors = "coerce")
df["Monthly_Spend"]

0       23066.19
1            NaN
2       28536.34
3       12869.71
4       34163.02
          ...
2035     8455.42
2036    34087.69
2037    26518.74
2038    20943.11
2039    48511.32
Name: Monthly_Spend, Length: 2040, dtype: float64

In [72]:
monthly_median= df['Monthly_Spend'].median()
monthly_median

24646.77

In [73]:
df['Monthly_Spend'] = df['Monthly_Spend'].fillna(monthly_median).astype(int)
df['Monthly_Spend']

0       23066
1       24646
2       28536
3       12869
4       34163
        ...
2035     8455
2036    34087
2037    26518
2038    20943
2039    48511
Name: Monthly_Spend, Length: 2040, dtype: int64

### Q14. Clean Transactions
### The Transactions column contains invalid strings.
### Convert it to numeric and replace invalid values with the median number of transactions.
### Then convert the final column to integer.

In [78]:
df["Transactions"] = pd.to_numeric(df["Transactions"],errors = "coerce")
df["Transactions"]

0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Transactions, Length: 2040, dtype: float64

In [79]:
trans_median= df['Monthly_Spend'].median()
trans_median

24646.0

In [80]:
df['Transactions'] = df['Transactions'].fillna(trans_median).astype(int)
df['Transactions']

0       135
1       106
2       146
3       115
4        94
       ...
2035    119
2036    134
2037     87
2038    107
2039    119
Name: Transactions, Length: 2040, dtype: int64

### Q15. Clean Satisfaction Score
### Clean Satisfaction_Score.
### Replace missing/invalid values using the mean Satisfaction Score.
### Then convert the column to float.

In [81]:
df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"],errors = "coerce")
df["Satisfaction_Score"]

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2040, dtype: float64

In [83]:
satis_mean= df['Satisfaction_Score'].mean()
satis_mean

np.float64(5.595907928388747)

In [85]:
df['Satisfaction_Score'] = df['Satisfaction_Score'].fillna(satis_mean).astype(float)
df['Satisfaction_Score']

0       3.0
1       8.0
2       6.0
3       9.0
4       3.0
       ...
2035    8.0
2036    2.0
2037    1.0
2038    9.0
2039    3.0
Name: Satisfaction_Score, Length: 2040, dtype: float64

# Part 4 — Date Cleaning

### Q16. Investigate Join_Date
### Inspect the Join_Date column.
### Identify the problems caused by:
### • Missing dates
### • Different date formats
### • Invalid date strings
### Do not clean it yet.

In [87]:
df['Join_Date'].head(7)

0    2022-08-15 0:00:00
1    2025-01-11 0:00:00
2    2024-08-01 0:00:00
3    2021-05-15 0:00:00
4    2026-02-03 0:00:00
5    2023-06-04 0:00:00
6    2024-01-16 0:00:00
Name: Join_Date, dtype: object

In [88]:
df['Join_Date'].isnull().sum()

np.int64(102)

In [90]:
df['Join_Date'].dropna().unique()

array(['2022-08-15 0:00:00', '2025-01-11 0:00:00', '2024-08-01 0:00:00',
       ..., '2025-09-10 0:00:00', '2022-10-17 0:00:00',
       '2023-08-26 0:00:00'], shape=(1225,), dtype=object)

In [92]:
Ap_date = pd.to_datetime(df["Join_Date"], errors="coerce")
Ap_date

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

### Q17. Convert Join_Date
### Convert Join_Date into a proper Pandas datetime column.
### Any invalid dates should become missing values.

In [93]:
Join_Date = pd.to_datetime(df["Join_Date"], errors="coerce")
Join_Date

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

In [94]:
df['Join_Date'].dtype

dtype('O')

In [96]:
df['Join_Date'].isnull().sum()

np.int64(102)

### Q18. Handle missing dates
### After conversion, find how many missing dates remain.
### Then replace missing dates appropriately using a reasonable date-based strategy.

In [98]:
missing_dates =df['Join_Date'].isna().sum()
missing_dates

np.int64(102)

# Part 5 — Categorical Cleaning

### Q19. Clean City
### The City column contains values such as:
### Mumbai
### mumbai
### Mumbai
### mumbai
### Standardize the values so that logically identical cities are represented consistently.
### Then check the unique frequency distribution.

In [103]:
df["City"] = df["City"].replace({"mumbai":"Mumbai"
})
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,.fillAnnual_Income
0,101317,55.0,44033.0,111350,772,3,Bangalore,SME,Agent,2022-08-15 0:00:00,Yes,Low,23066,135,3.0,44033.0
1,101001,32.0,215546.0,254378,374,8,Delhi,Retail,Agent,2025-01-11 0:00:00,Yes,High,24646,106,8.0,215546.0
2,101069,23.0,226403.0,159975,668,12,Chennai,Premium,Agent,2024-08-01 0:00:00,No,Medium,28536,146,6.0,226403.0
3,101968,66.0,87824.0,295741,315,14,Mumbai,Premium,Agent,2021-05-15 0:00:00,Yes,High,12869,115,9.0,87824.0
4,100530,67.0,31570.0,242423,370,4,bangalore,Retail,Agent,2026-02-03 0:00:00,No,High,34163,94,3.0,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490,677,12,Hyderabad,Retail,Agent,2021-07-10 0:00:00,No,Medium,8455,119,8.0,88530.0
2036,101295,31.0,205738.0,270989,392,8,Mumbai,Corporate,Agent,2025-07-05 0:00:00,Yes,High,34087,134,2.0,205738.0
2037,100861,25.0,211994.0,160507,737,8,Kolkata,Retail,Online,2022-10-17 0:00:00,Yes,Low,26518,87,1.0,211994.0
2038,101460,64.0,30105.0,32117,794,8,Bangalore,Retail,Agent,2023-08-26 0:00:00,No,Low,20943,107,9.0,30105.0
2039,101127,55.0,248332.0,274980,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.0,248332.0

In [104]:
df["City"] = df["City"].replace({"mumbai":"Mumbai","MUMBAI":"Mumbai"
})
df["City"].value_counts()

City
Mumbai       314
Hyderabad    278
Delhi        273
Kolkata      262
Pune         256
Chennai      242
Bangalore    236
hyderabad     20
bangalore     18
pune          18
delhi         15
kolkata       14
chennai       13
Name: count, dtype: int64

### Q20. Analyze Segment
### Check the frequency of:
### Retail
### SME
### Corporate
### Premium
### Also determine whether missing values exist.
### Then replace missing Segment values with the most appropriate category based on your
### analysis.

In [120]:
print(df['Segment'].isna().sum())

105

In [119]:
print(df['Segment'].value_counts())

Segment
Premium      523
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

In [121]:
# replace missing Segment values:
df['Segment'] = df['Segment'].fillna(df['Segment'].mode()[0])
df['Segment']

0             SME
1          Retail
2         Premium
3         Premium
4          Retail
          ...
2035       Retail
2036    Corporate
2037       Retail
2038       Retail
2039       Retail
Name: Segment, Length: 2040, dtype: object

In [122]:
df['Segment'].value_counts()

Segment
Premium      628
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

### Q21. Clean Active
### Active is supposed to be a binary column, but it contains:
### Yes
### No
### Y
### N
### YES
### NO
### yes
### no
### 1
### 0
### Transform these into a consistent representation:
### Yes
### No
### Then verify the result with value_counts().
### Use: replace(), value_counts()

In [125]:
df['Active'].value_counts()

Active
Yes    1313
No      546
0        17
Y        17
N        16
no       16
NO       15
YES      15
yes      14
1        12
Name: count, dtype: int64

In [127]:
df['Active'] = df['Active'].replace({'Y': 'Yes','YES': 'Yes','yes': 'Yes','N': 'No','NO': 'No','no': 'No',1: 'Yes',0: 'No'
})
df['Active']

0       Yes
1       Yes
2        No
3       Yes
4        No
       ...
2035     No
2036    Yes
2037    Yes
2038     No
2039    Yes
Name: Active, Length: 2040, dtype: object

In [128]:
df['Active'].value_counts()

Active
Yes    1359
No      593
0        17
1        12
Name: count, dtype: int64

### Q22. Clean Risk_Level
### Check the distribution of:
### High
### Medium
### Low
### Verify whether missing values exist.
### Then display the final class distribution.

In [135]:
df['Risk_Level'].value_counts()
df['Risk_Level']

0          Low
1         High
2       Medium
3         High
4         High
         ...
2035    Medium
2036      High
2037       Low
2038       Low
2039       Low
Name: Risk_Level, Length: 2040, dtype: object

In [132]:
df['Risk_Level'].isnull().sum()

np.int64(0)

In [134]:
df['Risk_Level'].value_counts(dropna=False)
df['Risk_Level']

0          Low
1         High
2       Medium
3         High
4         High
         ...
2035    Medium
2036      High
2037       Low
2038       Low
2039       Low
Name: Risk_Level, Length: 2040, dtype: object

# Part 6 — Column Transformation

### Q23. Rename columns
### Rename these columns:
### Customer_ID → Customer_ID
### Annual_Income → AnnualIncome
### Account_Balance → AccountBalance
### Credit_Score → CreditScore
### Tenure_Years → Tenure
### Join_Date → CustomerJoinDate
### Risk_Level → RiskLevel
### Monthly_Spend → MonthlySpend
### Satisfaction_Score → SatisfactionScore

In [136]:
df = df.rename(columns={'Customer_ID': 'Customer_ID','Annual_Income': 'AnnualIncome','Account_Balance': 'AccountBalance',
                        'Credit_Score': 'CreditScore','Tenure_Years': 'Tenure','Join_Date': 'CustomerJoinDate','Risk_Level':'RiskLevel',
                        'Monthly_Spend': 'MonthlySpend','Satisfaction_Score': 'SatisfactionScore'
})

df.columns

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore',
       '.fillAnnual_Income'],
      dtype='object')

### Q24. Add a prefix
### Add:
### Customer_
### to every column.
### Example:
### Age
### becomes:
### Customer_Age
### Use: add_prefix()

In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\customer_analytics - customer_analytics.csv")

In [4]:
df1 = df.add_prefix('Customer_')

df1.columns

Index(['Customer_Customer_ID', 'Customer_Age', 'Customer_Annual_Income',
       'Customer_Account_Balance', 'Customer_Credit_Score',
       'Customer_Tenure_Years', 'Customer_City', 'Customer_Segment',
       'Customer_Channel', 'Customer_Join_Date', 'Customer_Active',
       'Customer_Risk_Level', 'Customer_Monthly_Spend',
       'Customer_Transactions', 'Customer_Satisfaction_Score'],
      dtype='object')

### Q25. Remove unnecessary column
### Determine whether Customer_ID should be retained for analysis.
### Create a cleaned DataFrame without the identifier column.
### Use: drop()

In [7]:
df2 = df.drop('Customer_ID',axis = 1)
df2
df2.columns

Index(['Age', 'Annual_Income', 'Account_Balance', 'Credit_Score',
       'Tenure_Years', 'City', 'Segment', 'Channel', 'Join_Date', 'Active',
       'Risk_Level', 'Monthly_Spend', 'Transactions', 'Satisfaction_Score'],
      dtype='object')

In [9]:
df.to_csv("Santosh.csv")