In [129]:
import pandas as pd
df=pd.read_csv("C:\\Users\\MY PC\\OneDrive\\Desktop\\Data for pandas\\Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [130]:
# Challenge 1 – Complete Data Cleaning
# Your manager gives you a messy dataset.
# Perform all of the following:
#• Load the dataset.
import pandas as pd
df=pd.read_csv("C:\\Users\\MY PC\\OneDrive\\Desktop\\Data for pandas\\Task_dataset.csv")
"""• Display dataset information.
• Find missing values.
• Remove duplicate rows.
• Fill missing values:
o Age → median
o Balance → mean
• Rename:
o Target → CustomerStatus
o AnnualIncome → Income
 • Display information again."""
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [131]:
#• Display dataset information.
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]

In [132]:
#• Find missing values.
df.isnull().sum()
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]

In [133]:
#• Remove duplicate rows.
df.duplicated().sum()
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]

In [134]:
#o Age → median
df['Age'] = df['Age'].fillna(df['Age'].median())
print(df.head(15))

    CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0        10001  58.0       49184.0      2139          581        NaN       2
1        10002  65.0      162964.0      6197          732    6356.54       1
2        10003  56.0       26956.0     37281          503  143203.92       8
3        10004  55.0       92926.0       925          463  139627.88       5
4        10005  66.0      108236.0      7198          394   75985.46       5
5        10006  69.0       31390.0     48323          770  107245.62       6
6        10007  58.0      182141.0     24200          891   38457.72       1
7        10008  67.0       95861.0      5729          538  173296.73       6
8        10009  41.0       62638.0     24760          663   41901.41       4
9        10010  22.0      179680.0     42113          475  106827.98       3
10       10011  44.0      187772.0     45599          870   43923.03       5
11       10012  69.0      102694.0     26790          574   13237.72       9
12       10013  59.0      150870.0     26428          769   28574.32       2
13       10014  52.0       88876.0     49456          898   85686.77       9
14       10015  26.0      153569.0     32843          393  151156.43       1

   Geography  Gender    Segment Target
0     France    Male        SME   Stay
1        USA    Male        SME  Churn
2     Canada    Male  Corporate   Stay
3        NaN    Male     Retail  Churn
4         UK   Other  Corporate  Churn
5      India   Other  Corporate   Stay
6      India   Other     Retail  Churn
7         UK  Female        SME   Stay
8     France   Other        SME   Stay
9        USA  Female  Corporate  Churn
10     India     NaN     Retail   Stay
11    France  Female     Retail  Churn
12       USA   Other        SME   Stay
13    Canada  Female     Retail   Stay
14       USA   Other     Retail  Churn

In [135]:
#o Balance → mean
df['Balance'] = df['Balance'].fillna(df['Balance'].mean())
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore        Balance  \
0          10001  58.0       49184.0      2139          581   97523.535666
1          10002  65.0      162964.0      6197          732    6356.540000
2          10003  56.0       26956.0     37281          503  143203.920000
3          10004  55.0       92926.0       925          463  139627.880000
4          10005  66.0      108236.0      7198          394   75985.460000
...          ...   ...           ...       ...          ...            ...
1015       10450  43.0      173620.0      7121          644   60353.030000
1016       10753  25.0       54490.0     13794          303  124512.070000
1017       10810  49.0       82062.0     47170          813   53850.090000
1018       10267  38.0           NaN     10424          722  138100.050000
1019       10059  62.0       97504.0     36833          430   97523.535666

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]

In [136]:
#• Rename:
#o Target → CustomerStatus
df.rename(columns={'Target': 'CustomerStatus'}, inplace=True)
print(df)

#o AnnualIncome → Income
df.rename(columns={'AnnualIncome': 'Income'}, inplace=True)
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore        Balance  \
0          10001  58.0       49184.0      2139          581   97523.535666
1          10002  65.0      162964.0      6197          732    6356.540000
2          10003  56.0       26956.0     37281          503  143203.920000
3          10004  55.0       92926.0       925          463  139627.880000
4          10005  66.0      108236.0      7198          394   75985.460000
...          ...   ...           ...       ...          ...            ...
1015       10450  43.0      173620.0      7121          644   60353.030000
1016       10753  25.0       54490.0     13794          303  124512.070000
1017       10810  49.0       82062.0     47170          813   53850.090000
1018       10267  38.0           NaN     10424          722  138100.050000
1019       10059  62.0       97504.0     36833          430   97523.535666

      Tenure Geography  Gender    Segment CustomerStatus
0          2    France    Male        SME           Stay
1          1       USA    Male        SME          Churn
2          8    Canada    Male  Corporate           Stay
3          5       NaN    Male     Retail          Churn
4          5        UK   Other  Corporate          Churn
...      ...       ...     ...        ...            ...
1015       2       USA   Other  Corporate           Stay
1016       4     India     NaN  Corporate          Churn
1017       8   Germany  Female     Retail           Stay
1018       6   Germany   Other  Corporate           Stay
1019      10    Canada   Other        NaN          Churn

[1020 rows x 11 columns]
      CustomerID   Age    Income  Spending  CreditScore        Balance  \
0          10001  58.0   49184.0      2139          581   97523.535666
1          10002  65.0  162964.0      6197          732    6356.540000
2          10003  56.0   26956.0     37281          503  143203.920000
3          10004  55.0   92926.0       925          463  139627.880000
4          10005  66.0  108236.0      7198          394   75985.460000
...          ...   ...       ...       ...          ...            ...
1015       10450  43.0  173620.0      7121          644   60353.030000
1016       10753  25.0   54490.0     13794          303  124512.070000
1017       10810  49.0   82062.0     47170          813   53850.090000
1018       10267  38.0       NaN     10424          722  138100.050000
1019       10059  62.0   97504.0     36833          430   97523.535666

      Tenure Geography  Gender    Segment CustomerStatus
0          2    France    Male        SME           Stay
1          1       USA    Male        SME          Churn
2          8    Canada    Male  Corporate           Stay
3          5       NaN    Male     Retail          Churn
4          5        UK   Other  Corporate          Churn
...      ...       ...     ...        ...            ...
1015       2       USA   Other  Corporate           Stay
1016       4     India     NaN  Corporate          Churn
1017       8   Germany  Female     Retail           Stay
1018       6   Germany   Other  Corporate           Stay
1019      10    Canada   Other        NaN          Churn

[1020 rows x 11 columns]

In [137]:
# • Display information again.
df.head()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn

In [138]:
# Challenge 2 – Banking Report:
# The bank wants a numeric report.
    # Tasks
# • Select only numeric columns.
df.select_dtypes(include = 'number')
print(df)
"""
 • Display summary statistics.
 • Convert Age and CreditScore to float.
 • Display information again.
"""

      CustomerID   Age    Income  Spending  CreditScore        Balance  \
0          10001  58.0   49184.0      2139          581   97523.535666
1          10002  65.0  162964.0      6197          732    6356.540000
2          10003  56.0   26956.0     37281          503  143203.920000
3          10004  55.0   92926.0       925          463  139627.880000
4          10005  66.0  108236.0      7198          394   75985.460000
...          ...   ...       ...       ...          ...            ...
1015       10450  43.0  173620.0      7121          644   60353.030000
1016       10753  25.0   54490.0     13794          303  124512.070000
1017       10810  49.0   82062.0     47170          813   53850.090000
1018       10267  38.0       NaN     10424          722  138100.050000
1019       10059  62.0   97504.0     36833          430   97523.535666

      Tenure Geography  Gender    Segment CustomerStatus
0          2    France    Male        SME           Stay
1          1       USA    Male        SME          Churn
2          8    Canada    Male  Corporate           Stay
3          5       NaN    Male     Retail          Churn
4          5        UK   Other  Corporate          Churn
...      ...       ...     ...        ...            ...
1015       2       USA   Other  Corporate           Stay
1016       4     India     NaN  Corporate          Churn
1017       8   Germany  Female     Retail           Stay
1018       6   Germany   Other  Corporate           Stay
1019      10    Canada   Other        NaN          Churn

[1020 rows x 11 columns]

'\n • Display summary statistics.\n • Convert Age and CreditScore to float.\n • Display information again.\n'

In [139]:
# • Display summary statistics.
df.describe()
print(df)

      CustomerID   Age    Income  Spending  CreditScore        Balance  \
0          10001  58.0   49184.0      2139          581   97523.535666
1          10002  65.0  162964.0      6197          732    6356.540000
2          10003  56.0   26956.0     37281          503  143203.920000
3          10004  55.0   92926.0       925          463  139627.880000
4          10005  66.0  108236.0      7198          394   75985.460000
...          ...   ...       ...       ...          ...            ...
1015       10450  43.0  173620.0      7121          644   60353.030000
1016       10753  25.0   54490.0     13794          303  124512.070000
1017       10810  49.0   82062.0     47170          813   53850.090000
1018       10267  38.0       NaN     10424          722  138100.050000
1019       10059  62.0   97504.0     36833          430   97523.535666

      Tenure Geography  Gender    Segment CustomerStatus
0          2    France    Male        SME           Stay
1          1       USA    Male        SME          Churn
2          8    Canada    Male  Corporate           Stay
3          5       NaN    Male     Retail          Churn
4          5        UK   Other  Corporate          Churn
...      ...       ...     ...        ...            ...
1015       2       USA   Other  Corporate           Stay
1016       4     India     NaN  Corporate          Churn
1017       8   Germany  Female     Retail           Stay
1018       6   Germany   Other  Corporate           Stay
1019      10    Canada   Other        NaN          Churn

[1020 rows x 11 columns]

In [140]:
# • Convert Age and CreditScore to float.
df[['Age', 'CreditScore']] = df[['Age', 'CreditScore']].astype(float)
print(df)

      CustomerID   Age    Income  Spending  CreditScore        Balance  \
0          10001  58.0   49184.0      2139        581.0   97523.535666
1          10002  65.0  162964.0      6197        732.0    6356.540000
2          10003  56.0   26956.0     37281        503.0  143203.920000
3          10004  55.0   92926.0       925        463.0  139627.880000
4          10005  66.0  108236.0      7198        394.0   75985.460000
...          ...   ...       ...       ...          ...            ...
1015       10450  43.0  173620.0      7121        644.0   60353.030000
1016       10753  25.0   54490.0     13794        303.0  124512.070000
1017       10810  49.0   82062.0     47170        813.0   53850.090000
1018       10267  38.0       NaN     10424        722.0  138100.050000
1019       10059  62.0   97504.0     36833        430.0   97523.535666

      Tenure Geography  Gender    Segment CustomerStatus
0          2    France    Male        SME           Stay
1          1       USA    Male        SME          Churn
2          8    Canada    Male  Corporate           Stay
3          5       NaN    Male     Retail          Churn
4          5        UK   Other  Corporate          Churn
...      ...       ...     ...        ...            ...
1015       2       USA   Other  Corporate           Stay
1016       4     India     NaN  Corporate          Churn
1017       8   Germany  Female     Retail           Stay
1018       6   Germany   Other  Corporate           Stay
1019      10    Canada   Other        NaN          Churn

[1020 rows x 11 columns]

In [141]:
# • Display information again.
df.head()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581.0,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn

In [142]:
# Challenge 3 – Duplicate Investigation
# Find duplicate customers.
# Then
# • Count duplicate rows.
# • Remove duplicates.
# • Print information before and after removing duplicates.
# • Show the last 20 rows.
df.duplicated().sum()

np.int64(20)

In [143]:
# • Remove duplicates.
df.drop_duplicates(inplace = True)

In [144]:
# • Print information before and after removing duplicates.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

In [145]:
# • Show the last 20 rows.
df.tail(20)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
980,10981,41.0,199633.0,8498,847.0,173390.590000,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541.0,59484.580000,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334.0,97523.535666,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732.0,175352.250000,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730.0,120423.190000,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488.0,126031.270000,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621.0,115161.870000,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720.0,158528.460000,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635.0,159905.730000,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884.0,44897.430000,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773.0,39653.240000,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452.0,17812.250000,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764.0,165451.490000,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594.0,149288.610000,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493.0,83666.200000,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,NaN,Stay

In [146]:
""" Challenge 4 – HR Department
HR wants better column names.
 Rename
CustomerID → Employee_ID
Age → EmployeeAge
Gender → EmployeeGender
AnnualIncome → Salary
Target → PromotionStatus
Then
• Add prefix
HR_
to every column.
Display 10 random records.
"""
# CustomerID → Employee_ID
# Age → EmployeeAge
# Gender → EmployeeGender
# AnnualIncome → Salary
# Target → PromotionStatus
df.rename(columns={'CustomerID':'Employee_ID','Age':'EmployeeAge','Gender':'EmployeeGender','AnnualIncome':'Salary',
                 'Target':'PromotionStatus' },inplace = True)

In [147]:
df = df.add_prefix("Hr_")

In [148]:
df.sample()

,Hr_Employee_ID,Hr_EmployeeAge,Hr_Income,Hr_Spending,Hr_CreditScore,Hr_Balance,Hr_Tenure,Hr_Geography,Hr_EmployeeGender,Hr_Segment,Hr_CustomerStatus
563,10564,41.0,96958.0,14816,843.0,94971.44,8,France,Male,Retail,Stay

In [151]:
""" 5 – Finance Cleaning
Finance department reports missing values.
task
fill
AnnualIncome → Median
Balance → Mean
Age → Median
Then
Generate descriptive statistics.
"""
# AnnualIncome → Median
df["Hr_Income"].median()

112347.5

In [152]:
df["Hr_Balance"].mean()

np.float64(97555.86427328172)

In [153]:
df['Hr_EmployeeAge'].median()

44.0

In [ ]:
df.describe()

In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\MY PC\\OneDrive\\Desktop\\Data for pandas\\Task_dataset.csv")
df.head(5)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [9]:
""" 6  Data Type Audit
The company says
Age and AnnualIncome are stored incorrectly.
Tasks
Convert
Age → int
AnnualIncome → float
Balance → float
Target → string
Print information.
"""
import numpy as np
print(df["Age"].isna().sum())

df["Age"] = df["Age"].replace([np.inf, -np.inf], np.nan)

# Fill missing Age with median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Convert to integer
df["Age"] = df["Age"].astype(int)

df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

print(df)
print(df.info())

0
      CustomerID  Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0          10001   58       49184.0      2139          581        NaN       2
1          10002   65      162964.0      6197          732    6356.54       1
2          10003   56       26956.0     37281          503  143203.92       8
3          10004   55       92926.0       925          463  139627.88       5
4          10005   66      108236.0      7198          394   75985.46       5
...          ...  ...           ...       ...          ...        ...     ...
1015       10450   43      173620.0      7121          644   60353.03       2
1016       10753   25       54490.0     13794          303  124512.07       4
1017       10810   49       82062.0     47170          813   53850.09       8
1018       10267   38           NaN     10424          722  138100.05       6
1019       10059   62       97504.0     36833          430        NaN      10

     Geography  Gender    Segment Target
0       France    Male        SME   Stay
1          USA    Male        SME  Churn
2       Canada    Male  Corporate   Stay
3          NaN    Male     Retail  Churn
4           UK   Other  Corporate  Churn
...        ...     ...        ...    ...
1015       USA   Other  Corporate   Stay
1016     India     NaN  Corporate  Churn
1017   Germany  Female     Retail   Stay
1018   Germany   Other  Corporate   Stay
1019    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB
None