# Pandas + NumPy Data Cleaning

# 1. Load the CSV using Pandas and display the first 10 rows.

In [2]:
import pandas as pd 

df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\customer_data - customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

# 2. Check the number of rows and columns in the dataset.

In [3]:
df.shape

(2000, 15)

# 3. Display all column names and identify which column names contain
# leading/trailing spaces or inconsistent capitalization.

In [4]:
for i in df.columns:
    print(i)

Customer ID
Age
income_usd
credit Score
tenure_years
monthly_visits
satisfaction
City
customer_segment
gender
is_active
churn_flag
signup_date
lead_source
notes_text

In [5]:
df.columns = df.columns.str.title()
df.head()

,Customer Id,Age,Income_Usd,Credit Score,Tenure_Years,Monthly_Visits,Satisfaction,City,Customer_Segment,Gender,Is_Active,Churn_Flag,Signup_Date,Lead_Source,Notes_Text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???

# 4. Check the data type of every column using Pandas.

In [6]:
df.dtypes

Customer Id          object
Age                  object
Income_Usd           object
Credit Score         object
Tenure_Years        float64
Monthly_Visits      float64
Satisfaction        float64
City                 object
Customer_Segment     object
Gender               object
Is_Active            object
Churn_Flag           object
Signup_Date          object
Lead_Source          object
Notes_Text           object
dtype: object

# 5. Calculate the number and percentage of missing values in every column.

In [7]:
for i in df.columns:
    print(df[i].isna().sum()/20)

1.0
16.55
22.0
18.0
12.9
14.0
19.95
15.0
19.0
12.0
17.0
8.0
12.0
21.0
32.8

# 6. Find the rows where Customer ID is missing.

In [8]:
df[df['Customer Id'].isna()]

,Customer Id,Age,Income_Usd,Credit Score,Tenure_Years,Monthly_Visits,Satisfaction,City,Customer_Segment,Gender,Is_Active,Churn_Flag,Signup_Date,Lead_Source,Notes_Text
162,NaN,18,61780.99213,715.4452325,10.137001,5.0,3.179153,Delhi,UNKNOWN,Female,NaN,No,2021-04-22,website,follow-up needed
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

# 7. Remove leading/trailing whitespace from all column names and convert them
# to lowercase with underscores.

In [9]:
df = df.columns.str.replace(" ","_" ,regex = True)
df

Index(['Customer_Id', 'Age', 'Income_Usd', 'Credit_Score', 'Tenure_Years',
       'Monthly_Visits', 'Satisfaction', 'City', 'Customer_Segment', 'Gender',
       'Is_Active', 'Churn_Flag', 'Signup_Date', 'Lead_Source', 'Notes_Text'],
      dtype='object')

# 8. Identify duplicate Customer ID values and count how many duplicates exist.

In [22]:
df['Customer ID'].duplicated().sum()

np.int64(19)

In [23]:
df[df['Customer ID'].duplicated()]

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

# 9. Remove duplicate customer records while keeping the first occurrence.

In [24]:
df = df.drop_duplicates(keep ='first')
df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

# 10.Find all unique values in the customer_segment column and identify
# inconsistent categories such as Consumer, consumer, consumer , etc.

In [27]:
df['customer_segment'].unique()

array(['consumer', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

In [28]:
df['customer_segment'].value_counts()

customer_segment
Consumer      666
SMB           395
Enterprise    293
consumer      121
UNKNOWN        76
SMB.           69
Name: count, dtype: int64

In [40]:
df.rename( {"Consumer":"consumer","SMB.":"SMB"})
df['customer_segment'].value_counts(dropna = False)

customer_segment
Consumer      787
Smb           395
NaN           381
Enterprise    293
Unknown        76
Smb.           69
Name: count, dtype: int64

# 11.Clean the customer_segment column by standardizing capitalization and whitespace.

In [51]:
df['customer_segment'] = df['customer_segment'].str.strip().str.title() 
df

0                                                            Consumer
1                                                            Consumer
2                                                            Consumer
3                                                          Enterprise
4                                                          Enterprise
                                          ...
1996                                                              Smb
1997                                                             Smb.
1998                                                              Smb
1999                                                         Consumer
customer_segment    0                     Consumer
1              ...
Name: customer_segment, Length: 2001, dtype: object

In [48]:
df['customer_segment'].unique()

array(['Consumer', 'Enterprise', 'Smb', nan, 'Smb.', 'Unknown'],
      dtype=object)

In [49]:
df['customer_segment'].value_counts()

customer_segment
Consumer      787
Smb           395
Enterprise    293
Unknown        76
Smb.           69
Name: count, dtype: int64

# 12.Find all unique values in the gender column and convert them into consistent
# categories such as Male and Female.

In [54]:
import pandas as pd 

df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\customer_data - customer_data.csv")
df.head(2)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.38215,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed

In [58]:
df['gender'].unique()
df['gender'] = df['gender'].str.strip().str.title()
df['gender'].unique()
df['gender'] = df['gender'].str.strip().str.upper().replace({
    "M":"Male",
    "F":"Female"
})
df['gender']
df['gender'].unique()

array([nan, 'MALE', 'Male', 'FEMALE', 'Female'], dtype=object)