In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\MY PC\\OneDrive\\Desktop\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [2]:
#1 Load the dataset and display the first 10 records.
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [3]:
# 2.Display the last 15 customers.
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
# 3.Show 7 random customer records.
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8711,8712,15673995,Tu,516,Spain,Female,65,9,102541.10,1,1,0,181490.42,0
6932,6933,15570970,Han,647,France,Female,42,9,0.00,2,1,1,51362.82,0
7551,7552,15752578,Yefimova,626,France,Female,37,2,133968.96,2,1,0,148689.65,0
7966,7967,15750574,Lumholtz,677,Spain,Female,34,4,0.00,2,1,1,6175.53,0
9650,9651,15646168,Ifeatu,834,Spain,Male,33,5,0.00,2,1,0,66285.18,0
1626,1627,15588248,Hs?,617,France,Female,28,0,0.00,2,1,1,7597.83,1
1830,1831,15572467,Chandler,506,France,Male,37,5,0.00,2,1,1,127543.81,0

In [12]:
# 4.Print complete dataset information and identify:
# • Total columns
# • Data type of each column
# • Missing values
print(df.columns)
print(df.dtypes)
print(df.isnull().sum())  # or df.info()

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')
RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [13]:
# 5.Find missing values in every column
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [25]:
# 6.Display only numerical columns.
print(df.select_dtypes(include='number').isnull().sum())

RowNumber          0
CustomerId         0
CreditScore        0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [18]:
# 7.Generate the statistical summary of numerical columns.
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [31]:
# 8.Find duplicate rows and print how many exist.
df.duplicated().sum()

np.int64(0)

In [27]:
# 9.Remove duplicate rows and store the cleaned dataset.
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

In [30]:
# 10.Count how many customers have exited and how many have not exited.
df["Exited"].value_counts(dropna = True)

Exited
0    7963
1    2037
Name: count, dtype: int64

In [40]:
# 11.Rename the following columns: CustomerId → Customer_ID, CreditScore → Credit_Score, EstimatedSalary → Salary, Exited → Churn
df.rename(columns = {"CustomerId":"CustomerID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"churn"},inplace = True)
df

,RowNumber,CustomerID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [42]:
# 12.Add the prefix Bank_to every column name.
df=df.add_prefix("Bank_")
df

,Bank_Bank_RowNumber,Bank_Bank_CustomerID,Bank_Bank_Surname,Bank_Bank_Credit_Score,Bank_Bank_Geography,Bank_Bank_Gender,Bank_Bank_Age,Bank_Bank_Tenure,Bank_Bank_Balance,Bank_Bank_NumOfProducts,Bank_Bank_HasCrCard,Bank_Bank_IsActiveMember,Bank_Bank_Salary,Bank_Bank_churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [52]:
# 13.Convert the Age column into float datatype.
df['Age']=df['Bank_Bank_Age'].astype(float)
df["Age"]
#df.dtypes

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64

In [58]:
# 14.Convert the Exited column into string datatype.
df['Bank_Bank_churn']=df['Bank_Bank_churn'].astype(str)
df["Bank_Bank_churn"]

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Bank_Bank_churn, Length: 10000, dtype: object

In [59]:
# 15.Suppose the Balance column has missing values. Replace them using the mean of the Balance column.
df['Bank_Bank_Balance'] = df['Bank_Bank_Balance'].fillna(df['Bank_Bank_Balance']).mean()
print(df['Bank_Bank_Balance'].head())

0    76485.889288
1    76485.889288
2    76485.889288
3    76485.889288
4    76485.889288
Name: Bank_Bank_Balance, dtype: float64

In [61]:
# 16.Suppose the Age column has missing values.
# Replace them using the median age.
df["Bank_Bank_Age"] = df["Bank_Bank_Age"].fillna(df["Bank_Bank_Age"].median())
df["Bank_Bank_Age"]

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Bank_Bank_Age, Length: 10000, dtype: int64

In [65]:
# 17.Display only the first five rows after renaming the columns.
df.head()

,Bank_Bank_RowNumber,Bank_Bank_CustomerID,Bank_Bank_Surname,Bank_Bank_Credit_Score,Bank_Bank_Geography,Bank_Bank_Gender,Bank_Bank_Age,Bank_Bank_Tenure,Bank_Bank_Balance,Bank_Bank_NumOfProducts,Bank_Bank_HasCrCard,Bank_Bank_IsActiveMember,Bank_Bank_Salary,Bank_Bank_churn,Age
0,1,15634602,Hargrave,619,France,Female,42,2,76485.889288,1,1,1,101348.88,1,42.0
1,2,15647311,Hill,608,Spain,Female,41,1,76485.889288,1,0,1,112542.58,0,41.0
2,3,15619304,Onio,502,France,Female,42,8,76485.889288,3,1,0,113931.57,1,42.0
3,4,15701354,Boni,699,France,Female,39,1,76485.889288,2,0,0,93826.63,0,39.0
4,5,15737888,Mitchell,850,Spain,Female,43,2,76485.889288,1,1,1,79084.10,0,43.0

In [64]:
# 18.Create a new DataFrame by dropping these columns:
# RowNumber
# CustomerId
# Surname
# Display the first 10 rows.
df1 = df.drop("Bank_Bank_RowNumber",axis = 1)
df2 = df1.drop("Bank_Bank_CustomerID",axis = 1)
df3 = df2.drop("Bank_Bank_Surname",axis = 1)
df3

,Bank_Bank_Credit_Score,Bank_Bank_Geography,Bank_Bank_Gender,Bank_Bank_Age,Bank_Bank_Tenure,Bank_Bank_Balance,Bank_Bank_NumOfProducts,Bank_Bank_HasCrCard,Bank_Bank_IsActiveMember,Bank_Bank_Salary,Bank_Bank_churn,Age
0,619,France,Female,42,2,76485.889288,1,1,1,101348.88,1,42.0
1,608,Spain,Female,41,1,76485.889288,1,0,1,112542.58,0,41.0
2,502,France,Female,42,8,76485.889288,3,1,0,113931.57,1,42.0
3,699,France,Female,39,1,76485.889288,2,0,0,93826.63,0,39.0
4,850,Spain,Female,43,2,76485.889288,1,1,1,79084.10,0,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,76485.889288,2,1,0,96270.64,0,39.0
9996,516,France,Male,35,10,76485.889288,1,1,1,101699.77,0,35.0
9997,709,France,Female,36,7,76485.889288,1,0,1,42085.58,1,36.0
9998,772,Germany,Male,42,3,76485.889288,2,1,0,92888.52,1,42.0
9999,792,France,Female,28,4,76485.889288,1,1,0,38190.78,0,28.0

In [69]:
df = pd.read_csv("C:\\Users\\MY PC\\OneDrive\\Desktop\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [70]:
# 19.Drop the Geography column and display dataset information again.
df.drop('Geography',axis = 1,inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(2)
memory usage: 1015.8+ KB

In [72]:
# 20.Rename NumOfProducts to Products and HasCrCard to CreditCard.
df.rename(columns = {"NumOfProducts":"Products","HasCrCard":"CreditCard"},inplace = True)
df

,RowNumber,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28,4,130142.79,1,1,0,38190.78,0