# Flight Price Datasets—Clean Questions

# 1. Load the Flight Price dataset into a Pandas DataFrame and display the first
# five rows.

In [1]:
import pandas as pd 
df = pd.read_csv("C:\\Users\MY PC\\Downloads\\Data_Train.xlsx - Sheet1.csv""")
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

# 2. Find the number of rows and columns in the dataset.

In [2]:
df.shape

(10683, 11)

# 3. Display all column names in the dataset.

In [4]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

# 4. Display the data types of all columns.

In [6]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

# 5. Use df.info() to inspect the structure of the dataset.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

# 6. Check the number of missing values in each column.

In [8]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

# 7. Check the percentage of missing values in each column.

In [9]:
df.isna().sum() * 100

Airline              0
Date_of_Journey      0
Source               0
Destination          0
Route              100
Dep_Time             0
Arrival_Time         0
Duration             0
Total_Stops        100
Additional_Info      0
Price                0
dtype: int64

# 8. Display the unique values and frequency of each value in the Airline column.

In [10]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [11]:
df['Airline'].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

# 9. Display the frequency distribution of Total_Stops, including missing values.

In [16]:
df['Total_Stops'].value_counts().isna()

Total_Stops
1 stop      False
non-stop    False
2 stops     False
3 stops     False
4 stops     False
Name: count, dtype: bool

# 10.Convert Date_of_Journey into a datetime format.

In [18]:
df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'],dayfirst=False)
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

# 11.Extract the day from Date_of_Journey and create a day column.

In [19]:
df['Date_of_Journey'] = df['Date_of_Journey'].dt.day

In [21]:
df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'],errors = "coerce")
df.head(4)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,1970-01-01 00:00:00.000000024,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1970-01-01 00:00:00.000000001,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,1970-01-01 00:00:00.000000009,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,1970-01-01 00:00:00.000000012,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218

# 12.Extract the month from Date_of_Journey and create a month column.

In [43]:
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey']).dt.month

In [23]:
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'],errors = "coerce")
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,1970-01-01 00:00:00.000000001,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1970-01-01 00:00:00.000000001,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,1970-01-01 00:00:00.000000001,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,1970-01-01 00:00:00.000000001,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,1970-01-01 00:00:00.000000001,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

# 13.Extract the year from Date_of_Journey and create a year column.

In [48]:
import pandas as pd

df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'],errors='coerce',dayfirst=True
)
df['year'] = df['Date_of_Journey'].dt.year
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,year
0,IndiGo,1970-01-01 00:00:00.000000001,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,1970
1,Air India,1970-01-01 00:00:00.000000001,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1970
2,Jet Airways,1970-01-01 00:00:00.000000001,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,1970
3,IndiGo,1970-01-01 00:00:00.000000001,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,1970
4,IndiGo,1970-01-01 00:00:00.000000001,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1970
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,1970-01-01 00:00:00.000000001,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,1970
10679,Air India,1970-01-01 00:00:00.000000001,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,1970
10680,Jet Airways,1970-01-01 00:00:00.000000001,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,1970
10681,Vistara,1970-01-01 00:00:00.000000001,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1970
10682,Air India,1970-01-01 00:00:00.000000001,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,1970

# 14.Drop the original Date_of_Journey column after extracting the required features.

In [49]:
df.drop('Date_of_Journey',axis = 1 ,inplace = True)

In [50]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'year'],
      dtype='object')

# 15.Convert Dep_Time into datetime format and extract the departure hour into Dep_Hour.

In [2]:
import pandas as pd 
df = pd.read_csv("C:\\Users\MY PC\\Downloads\\Data_Train.xlsx - Sheet1.csv""")
df.head(3)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882

In [3]:
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'],format='%H:%M',errors = "coerce")

df['Dep_Hour'] = df['Dep_Time'].dt.hour

df[['Dep_Time', 'Dep_Hour']].head()

             Dep_Time  Dep_Hour
0 1900-01-01 22:20:00        22
1 1900-01-01 05:50:00         5
2 1900-01-01 09:25:00         9
3 1900-01-01 18:05:00        18
4 1900-01-01 16:50:00        16

# 16.Extract the departure minute from Dep_Time and create Dep_Minute.

In [4]:
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'],format='%H:%M',errors = "coerce")

df['Dep_Minute'] = df['Dep_Time'].dt.minute

df[['Dep_Time', 'Dep_Minute']].head()

             Dep_Time  Dep_Minute
0 1900-01-01 22:20:00          20
1 1900-01-01 05:50:00          50
2 1900-01-01 09:25:00          25
3 1900-01-01 18:05:00           5
4 1900-01-01 16:50:00          50

# 17.Drop the original Dep_Time column after extracting the required features.

In [8]:
df.drop('Dep_Time',axis=1,inplace=True)
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,5,50
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,18,5
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,16,50

# 18.Extract only the time portion from Arrival_Time.

In [12]:
df['Arrival_Time'] = df['Arrival_Time'].str.split().str[0]
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10,2h 50m,non-stop,No info,3897,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,5,50
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,04:25,19h,2 stops,No info,13882,9,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,18,5
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,16,50

# 19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.

In [13]:
df['Arrival_Hour'] = pd.to_datetime(df['Arrival_Time'], format='%H:%M', errors='coerce').dt.hour

df['Arrival_Minute'] = pd.to_datetime(df['Arrival_Time'], format='%H:%M', errors='coerce').dt.minute

In [14]:
df[['Arrival_Time', 'Arrival_Hour', 'Arrival_Minute']].head()

  Arrival_Time  Arrival_Hour  Arrival_Minute
0        01:10             1              10
1        13:15            13              15
2        04:25             4              25
3        23:30            23              30
4        21:35            21              35

# 20.Drop the original Arrival_Time column after extracting the required features.

In [18]:
df.drop('Arrival_Time', axis=1,inplace=True ,errors ='ignore')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,22,20,1,10
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,5,50,13,15
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,25,4,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,18,5,23,30
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,16,50,21,35

# 21.Extract the hour component from Duration and create Duration_Hour. Handle
# invalid or missing extracted values appropriately.

In [19]:
df['Duration_Hour'] = df['Duration'].str.extract(r'(\d+)h')[0]

In [20]:
df['Duration_Hour'] = pd.to_numeric(df['Duration_Hour'], errors='coerce')

In [21]:
df[['Duration', 'Duration_Hour']].head()

  Duration  Duration_Hour
0   2h 50m            2.0
1   7h 25m            7.0
2      19h           19.0
3   5h 25m            5.0
4   4h 45m            4.0

# 22.Extract the minute component from Duration and create Duration_Minute.
# Handle invalid or missing extracted values appropriately.

In [22]:
df['Duration_Minute'] = df['Duration'].str.extract(r'(\d+)h')[0]

In [23]:
df['Duration_Minute'] = pd.to_numeric(df['Duration_Minute'], errors='coerce')
df[['Duration', 'Duration_Minute']].head()

  Duration  Duration_Minute
0   2h 50m              2.0
1   7h 25m              7.0
2      19h             19.0
3   5h 25m              5.0
4   4h 45m              4.0

# 23.Drop the original Duration column after creating the numerical duration
# features.

In [24]:
df.drop('Duration', axis=1,inplace=True) # ,errors ='ignore')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,22,20,1,10,2.0,2.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,5,50,13,15,7.0,7.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,25,4,25,19.0,19.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,18,5,23,30,5.0,5.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,16,50,21,35,4.0,4.0

# 24.Replace non-stop in Total_Stops with 0 stops.

In [25]:
df['Total_Stops'] = df['Total_Stops'].replace('non-stop', 0)

In [27]:
df['Total_Stops'].value_counts()

Total_Stops
1 stop     5625
0          3491
2 stops    1520
3 stops      45
4 stops       1
Name: count, dtype: int64

# 25.Extract only the numerical value from Total_Stops and convert the column into
# an integer data type. Handle missing or invalid values appropriately.

In [28]:
df['Total_Stops'] = df['Total_Stops'].astype(str).str.extract(r'(\d+)')[0]

In [29]:
df['Total_Stops'] = pd.to_numeric(df['Total_Stops'], errors='coerce')

In [37]:
df['Total_Stops'] = df['Total_Stops'].fillna(df['Total_Stops'].median())
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,0,No info,3897,22,20,1,10,2.0,2.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,5,50,13,15,7.0,7.0

In [35]:
df['Total_Stops'] = df['Total_Stops'].astype(int)
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,0,No info,3897,22,20,1,10,2.0,2.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,5,50,13,15,7.0,7.0

In [32]:
df['Total_Stops'].value_counts()

Total_Stops
1    5626
0    3491
2    1520
3      45
4       1
Name: count, dtype: int64

In [38]:
df['Total_Stops'].dtype

dtype('int64')

# 26.Split the Route column using → as the separator and create Route_1,
# Route_2, Route_3, Route_4, and Route_5.

In [42]:
df[['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']] = (
    df['Route'].str.split('→', n=4, expand=True)
)

In [43]:
df[['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']].head()

  Route_1 Route_2 Route_3 Route_4 Route_5
0    BLR      DEL    None    None    None
1    CCU     IXR     BBI      BLR    None
2    DEL     LKO     BOM      COK    None
3    CCU     NAG      BLR    None    None
4    BLR     NAG      DEL    None    None

# 27.Identify the missing values created in Route_3, Route_4, and Route_5 after
# splitting the route.

In [46]:
df[['Route_3', 'Route_4', 'Route_5']].isnull().sum()

Route_3     3492
Route_4     9117
Route_5    10637
dtype: int64