In [105]:
import pandas as pd

# Read Excel file
df = pd.read_excel(r"C:\Users\MY PC\Downloads\archive\Data_Train.xlsx")

# Convert and save as CSV
df.to_csv(r"C:\Users\MY PC\Downloads\archive\Data_Train.csv", index=False)

print("Excel file converted to CSV successfully!")
df.head()

Excel file converted to CSV successfully!

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [66]:
df.shape

(10683, 11)

In [67]:
df.info

<bound method DataFrame.info of            Airline Date_of_Journey    Source Destination  \
0           IndiGo      24/03/2019  Banglore   New Delhi
1        Air India       1/05/2019   Kolkata    Banglore
2      Jet Airways       9/06/2019     Delhi      Cochin
3           IndiGo      12/05/2019   Kolkata    Banglore
4           IndiGo      01/03/2019  Banglore   New Delhi
...            ...             ...       ...         ...
10678     Air Asia       9/04/2019   Kolkata    Banglore
10679    Air India      27/04/2019   Kolkata    Banglore
10680  Jet Airways      27/04/2019  Banglore       Delhi
10681      Vistara      01/03/2019  Banglore   New Delhi
10682    Air India       9/05/2019     Delhi      Cochin

                       Route Dep_Time  Arrival_Time Duration Total_Stops  \
0                  BLR → DEL    22:20  01:10 22 Mar   2h 50m    non-stop
1      CCU → IXR → BBI → BLR    05:50         13:15   7h 25m     2 stops
2      DEL → LKO → BOM → COK    09:25  04:25 10 Jun      19h     2 stops
3            CCU → NAG → BLR    18:05         23:30   5h 25m      1 stop
4            BLR → NAG → DEL    16:50         21:35   4h 45m      1 stop
...                      ...      ...           ...      ...         ...
10678              CCU → BLR    19:55         22:25   2h 30m    non-stop
10679              CCU → BLR    20:45         23:20   2h 35m    non-stop
10680              BLR → DEL    08:20         11:20       3h    non-stop
10681              BLR → DEL    11:30         14:10   2h 40m    non-stop
10682  DEL → GOI → BOM → COK    10:55         19:15   8h 20m     2 stops

      Additional_Info  Price
0             No info   3897
1             No info   7662
2             No info  13882
3             No info   6218
4             No info  13302
...               ...    ...
10678         No info   4107
10679         No info   4145
10680         No info   7229
10681         No info  12648
10682         No info  11753

[10683 rows x 11 columns]>

# Handling missing values

In [68]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [69]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [70]:
df['Source'].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [47]:
df['Route'].isnull().sum()

np.int64(1)

In [7]:
df.dropna(subset=['Route'], inplace=True)
df['Route'].isna().sum()

np.int64(0)

In [8]:
df.dropna(subset=['Route'],inplace=True)
df['Total_Stops'].isna().sum()

np.int64(0)

In [9]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

#  Standardize airline names

In [10]:
df['Airline'] = df['Airline'].str.strip().str.title()
df['Airline'].unique()

array(['Indigo', 'Air India', 'Jet Airways', 'Spicejet',
       'Multiple Carriers', 'Goair', 'Vistara', 'Air Asia',
       'Vistara Premium Economy', 'Jet Airways Business',
       'Multiple Carriers Premium Economy', 'Trujet'], dtype=object)

# Extract hours/minutes from duration

In [90]:
df['Duration'] = df['Duration'].str.replace('h ', ':').str.replace('m', '')

# • Convert price to numeric

In [12]:
df['Price'] =pd.to_numeric(df['Price'],errors='coerce')
df['Price']

0         3897
1         7662
2        13882
3         6218
4        13302
         ...
10678     4107
10679     4145
10680     7229
10681    12648
10682    11753
Name: Price, Length: 10682, dtype: int64

# • Extract number of stops

In [109]:
df = df.drop(["Route", "Additional_Info"], axis=1)

In [107]:
df['Total_Stops'].unique()

array([ 0.,  2.,  1.,  3., nan,  4.])

In [106]:
df['Total_Stops'] = df['Total_Stops'].map({
    'non-stop': 0,
    '1 stop': 1,
    '2 stops': 2,
    '3 stops': 3,
    '4 stops': 4
})

In [61]:
df['Arrival_Time'].unique()

array(['01:10', '13:15', '04:25', '23:30', '21:35', '11:25', '10:25',
       '05:05', '19:15', '23:00', '22:55', '13:55', '09:20', '19:50',
       '12:35', '19:20', '13:20', '06:50', '21:50', '08:15', '03:35',
       '12:55', '23:15', '21:00', '20:20', '16:45', '19:00', '18:10',
       '15:15', '08:35', '11:05', '14:15', '10:55', '00:15', '02:45',
       '12:00', '23:55', '01:30', '09:25', '15:25', '15:35', '08:30',
       '10:05', '14:30', '07:55', '10:35', '22:35', '04:40', '07:25',
       '20:45', '14:25', '22:30', '23:20', '07:40', '22:50', '14:35',
       '08:55', '18:50', '09:05', '01:35', '09:40', '16:25', '11:10',
       '17:05', '17:50', '23:10', '08:45', '07:45', '16:10', '00:55',
       '23:35', '20:00', '00:40', '21:45', '18:15', '03:25', '04:15',
       '21:10', '21:05', '09:45', '18:05', '22:00', '15:30', '08:50',
       '08:00', '19:35', '11:20', '10:15', '12:45', '02:20', '07:15',
       '11:50', '18:30', '19:45', '21:20', '20:05', '09:10', '22:20',
       '10:10', '01:00', '23:50', '12:20', '20:25', '22:45', '21:25',
       '14:05', '00:05', '19:55', '16:20', '07:05', '19:10', '12:05',
       '04:05', '19:40', '17:55', '17:25', '00:30', '23:40', '23:05',
       '00:50', '13:45', '09:15', '20:35', '07:10', '09:35', '14:20',
       '04:45', '10:30', '19:25', '05:35', '09:00', '22:40', '14:45',
       '13:25', '21:55', '10:45', '10:40', '13:00', '22:10', '18:35',
       '05:25', '22:15', '12:10', '12:15', '14:00', '02:15', '12:50',
       '17:15', '07:35', '23:45', '22:25', '12:25', '06:35', '01:20',
       '18:45', '09:30', '04:20', '10:50', '23:25', '22:05', '13:30',
       '13:35', '17:35', '08:20', '18:25', '10:20', '15:50', '11:30',
       '14:10', '00:25', '03:15', '15:55', '00:45', '04:35', '18:00',
       '12:30', '02:10', '00:20', '21:40', '08:40', '16:55', '20:30',
       '17:20', '00:35', '20:15', '14:50', '13:40', '16:50', '15:05',
       '17:45', '18:40', '03:10', '16:40', '09:50', '13:05', '17:40',
       '20:40', '17:10', '20:50', '00:10', '08:10', '16:15', '16:05',
       '10:00', '16:35', '18:20', '04:00', '21:15', '14:40', '01:45',
       '16:30', '11:55', '15:20', '20:10', '15:00', '15:45', '12:40',
       '15:10', '13:10', '11:15', '03:40', '16:00', '11:35'], dtype=object)

In [101]:
df['Duration'] = df['Duration'].str.replace('h ', ':').str.replace('m', '')

In [110]:
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,0.0,3897
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2.0,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,09:25,04:25 10 Jun,19h,2.0,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,18:05,23:30,5h 25m,1.0,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,16:50,21:35,4h 45m,1.0,13302
...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,19:55,22:25,2h 30m,0.0,4107
10679,Air India,27/04/2019,Kolkata,Banglore,20:45,23:20,2h 35m,0.0,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,08:20,11:20,3h,0.0,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,11:30,14:10,2h 40m,0.0,12648
10682,Air India,9/05/2019,Delhi,Cochin,10:55,19:15,8h 20m,2.0,11753

In [115]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Price              0
dtype: int64

In [116]:
df.dropna(subset=['Total_Stops'], inplace=True)
df['Total_Stops'].isna().sum()

np.int64(0)

In [117]:
df.to_csv("Airline_info.csv",index = False)
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,0.0,3897
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2.0,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,09:25,04:25 10 Jun,19h,2.0,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,18:05,23:30,5h 25m,1.0,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,16:50,21:35,4h 45m,1.0,13302
...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,19:55,22:25,2h 30m,0.0,4107
10679,Air India,27/04/2019,Kolkata,Banglore,20:45,23:20,2h 35m,0.0,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,08:20,11:20,3h,0.0,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,11:30,14:10,2h 40m,0.0,12648
10682,Air India,9/05/2019,Delhi,Cochin,10:55,19:15,8h 20m,2.0,11753